services:
  - type: web
    name: imageblower
    env: python
    buildCommand: pip install torch==2.0.1 && pip install -r requirements.txt
    startCommand: gunicorn app:app --chdir image-blower-backend --bind 0.0.0.0:$PORT
    plan: free