services:
  - type: web
    name: imageblower
    env: python
    plan: free
    buildCommand: |
      pip install torch==2.5.0
      pip install -r requirements.txt
    startCommand: |
      curl -L -o weights/RealESRGAN_x2plus.pth https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5/RealESRGAN_x2plus.pth &&
      python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
